import requests, shutil, datetime
import time

nazwa = datetime.datetime.now().strftime("%Y-%m-%d-%H-%M-%S") + '.zip'
paczka = 'https://media.forgecdn.net/files/2935/323/RLCraft+Server+Pack+1.12.2+-+Beta+v2.8.2.zip'
sidfile = open("./sid/" + '000' + '.txt',"r+")
sid = sidfile.read()
print(sid)
mailfile = open("./sid/" + '001' + '.txt',"r+")
mail = mailfile.read()
print(mail)
passwordfile = open("./sid/" + '002' + '.txt',"r+")
password = passwordfile.read()
print(password)
strona = 'https://craftserve.pl/s/' + sid + '/files/'
s = requests.session()
r = s.post('https://craftserve.pl/login', {'email': mail, 'password': password, 'send': ''})
r.raise_for_status()
s.post('https://craftserve.pl/s/' + sid + '/console', 'stop')
s.post('https://craftserve.pl/s/' + sid + '/files/?url', {'url_data': paczka})
time.sleep(10)
r = s.delete(strona + 'world/?allow_dir=true')
r = s.delete(strona + 'world_nether/?allow_dir=true')
r = s.delete(strona + 'world_the_end/?allow_dir=true')
r = s.delete(strona + 'plugins/?allow_dir=true')
r = s.delete(strona + 'mods/?allow_dir=true')
r = s.delete(strona + 'server.properties/?allow_dir=true')
r = s.delete(strona + 'logs/?allow_dir=true')
r = s.delete(strona + 'cache/?allow_dir=true')
r = s.delete(strona + 'config/?allow_dir=true')
r = s.delete(strona + 'scripts/?allow_dir=true')
r = s.delete(strona + 'structures/?allow_dir=true')
r = s.delete(strona + 'resources/?allow_dir=true')
r = s.delete(strona + 'resourcepacks/?allow_dir=true')
r = s.delete(strona + 'libraries/?allow_dir=true')
r = s.delete(strona + 'llibrary/?allow_dir=true')
r = s.post('https://craftserve.pl/s/' + sid + '/files_unzip/RLCraft+Server+Pack+1.12.2+-+Beta+v2.8.2.zip', {'destination': '/'})
time.sleep(10)
r = s.delete(strona + 'RLCraft+Server+Pack+1.12.2+-+Beta+v2.8.2.zip')
r = s.post('https://craftserve.pl/s/' + sid + '/settings/engines', {'engine': '095e58e8-c63d-4e44-bb7b-d827781c5384', 'step': '1', 'eula': '0', 'java_version': '1'})
r.raise_for_status()
